apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  labels:
    build: shilpi-app
  name: shilpi-app
  namespace: test-ace
spec:
  failedBuildsHistoryLimit: 5
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: shilpi-app:latest
  postCommit: {}
  resources: {}
  runPolicy: Serial
  source:
    git:
      uri: https://github.com/BharatBabbar28/mvn_war_java.git
    type: Git
  strategy:
    sourceStrategy:
      from:
        kind: ImageStreamTag
        name: openjdk-11:latest
    type: Source
  successfulBuildsHistoryLimit: 5
  triggers:
  - type: ConfigChange
  - type: ImageChange
