apiVersion: project.openshift.io/v1
kind: Project
metadata:
  name: s2i-test
spec: {}
status:
  phase: Active
  
---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: test
  namespace: s2i-test
spec:
  lookupPolicy:
    local: false

---
apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: test
  namespace: s2i-test
spec:
  completionDeadlineSeconds: 600
  output:
    to:
      kind: ImageStreamTag
      name: test:latest
  postCommit:
    script: |
      echo "Uploading finished"
  source:
    binary:
      asFile: sparkjava-hello-world-1.0.war
      type: Binary
  strategy:
    sourceStrategy:
      from:
        kind: ImageStreamTag
        name: java:8
        namespace: openshift
    type: Source
  triggers:
  - github:
      secret: SSVl4hBVpIa1NSDoU2Bk
    type: GitHub
  - generic:
      secret: F8skctaonalBRn1sVn_Y
    type: Generic
  resources:
    limits:
      cpu: "1"
      memory: 1Gi
    requests:
      cpu: 50m
      memory: 100Mi

